# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   app_logout
            # activate different ways to authenticate
            logout_on_user_change: true
            
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~
            provider: our_db_provider
            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            light_saml_sp:
                provider: our_db_provider       # user provider name configured in step 9
                user_creator: user_creator  # name of the user creator service created in step 10
                login_path: /saml/login
                check_path: /saml/login_check
                default_target_path: /
                require_previous_session: true
                
                # LightSAML options

                # provides username from the received SAML Response
                username_mapper: lightsaml_sp.username_mapper.simple

                # called in case provider didn't return a user to create a new user
                user_creator: ~

                # provides token attributes
                attribute_mapper: lightsaml_sp.attribute_mapper.simple

                # use string as username and create unauthenticated token w/out roles
                # in case creator didn't create a user
                force: false
            logout:
                path: /logout
            

    access_control:
        - { path: ^/secure, roles: ROLE_USER }
    encoders:
        AppBundle\Entity\User: bcrypt
